export const ERROR_CODE = {
  SESSION_REQUIRED: "SESSION_REQUIRED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  PAYMENT_INVALID: "PAYMENT_INVALID",
  ASSESSMENT_NOT_FOUND: "ASSESSMENT_NOT_FOUND",
  ASSESSMENT_INCOMPLETE: "ASSESSMENT_INCOMPLETE",
  ASSESSMENT_VERSION_CONFLICT: "ASSESSMENT_VERSION_CONFLICT",
  ASSESSMENT_ALREADY_COMPLETED: "ASSESSMENT_ALREADY_COMPLETED",
  STEP_OUT_OF_ORDER: "STEP_OUT_OF_ORDER",
  STEP_VALUE_INCONSISTENT: "STEP_VALUE_INCONSISTENT",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
